In [1]:
import pandas as pd
import numpy as np

In [28]:
user_item_matrix = np.array([[5,1,3,5],[np.nan,np.nan,np.nan,2],[4,np.nan,3,np.nan]])
user_item_matrix

array([[ 5.,  1.,  3.,  5.],
       [nan, nan, nan,  2.],
       [ 4., nan,  3., nan]])

In [29]:
#Fill missing with zeros
user_item_matrix = np.nan_to_num(user_item_matrix, nan=0.0)

In [30]:
u,s,vt = np.linalg.svd(user_item_matrix)
u.shape, s.shape , vt.shape

((3, 3), (3,), (4, 4))

# In case we use all latent features
Prediction Matrix ~ M

In [34]:
pred_ratings = np.dot(np.dot(u,np.diag(s)),vt[:3,:])
pred_ratings,user_item_matrix

(array([[ 5.00000000e+00,  1.00000000e+00,  3.00000000e+00,
          5.00000000e+00],
        [-9.46683961e-16,  5.07767737e-16, -7.84401048e-16,
          2.00000000e+00],
        [ 4.00000000e+00, -1.06674877e-16,  3.00000000e+00,
         -8.12706237e-16]]),
 array([[5., 1., 3., 5.],
        [0., 0., 0., 2.],
        [4., 0., 3., 0.]]))

In [35]:
# compute squared error
sum_square_errs = np.sum(np.sum((user_item_matrix-pred_ratings)**2))
sum_square_errs

1.328803200636662e-29

# Let's take a look at sigma matrix to choose options for Latent features

In [36]:
s

array([8.79824245, 3.3819105 , 0.39193263])

In [39]:
k = 2 
pred_ratings = np.dot(np.dot(u[:,:k],np.diag(s[:k])),vt[:k,:])
pred_ratings

array([[ 4.96367759,  0.89036847,  3.05498184,  5.02189148],
       [ 0.09443248,  0.28502456, -0.14294406,  1.94308563],
       [ 4.04239448,  0.12795881,  2.93582675, -0.02555111]])

In [40]:
# compute squared error
sum_square_errs = np.sum(np.sum((user_item_matrix-pred_ratings)**2))
sum_square_errs

0.15361118416557326

# My final comment, when we use all latent features it results some sort of overfitting, 
## sigma matrix's eigen values help us choose appropriate value for k